# Generated by Django 3.2.13 on 2023-05-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230503_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_products_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
